version: "3.9"

services:
  stakeholders-service:
    build:
      context: .
      dockerfile: services/stakeholders-service/Dockerfile
    container_name: stakeholders-service
    ports:
      - "8081:8080"

  blog-service:
    build:
      context: .
      dockerfile: services/blog-service/Dockerfile
    container_name: blog-service
    ports:
      - "8082:8080"

  tourist-app-ui:
    image: node:18-alpine
    container_name: tourist-app-ui
    working_dir: /app
    command: sh -c "cd frontend/tourist-app-ui && npm install && npm start -- --host 0.0.0.0 --port 4200"
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    depends_on:
      - stakeholders-service
      - blog-service
