{
 "title": "Service Logs",
 "panels": [
  {
   "title": "All Service Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=~\".+\"}"
    }
   ]
  },
  {
   "title": "Stakeholders Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container=\"/stakeholders-service\"}"
    }
   ]
  },
  {
   "title": "Purchase Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{container=\"/purchase-service\"}"
    }
   ]
  },
  {
   "title": "Tour Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"/tour-service\"}"
    }
   ]
  },
  {
   "title": "Gateway RPC Adapter Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"/gateway-rpc-adapter\"}"
    }
   ]
  },
  {
   "title": "Blog Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "{container=\"/blog-service\"}"
    }
   ]
  },
  {
   "title": "Follower Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{container=\"/follower-service\"}"
    }
   ]
  }
 ]
}